trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Evita el checkout automático de Azure y define uno limpio
- checkout: self
  fetchDepth: 1

# Mensaje simple (puedes quitarlo si quieres)
- script: echo "Pipeline ejecutado correctamente para proyecto HTML."
  displayName: "Verificación"

# Publicar la página como artefacto (opcional)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '.'      # Publica todo el repo
    ArtifactName: 'sitio'   # Nombre del artefacto
  displayName: "Publicar artefactos HTML"
